export const manufacturers = [
  "Toyota",
  "Volkswagen",
  "Ford",
  "Chevrolet",
  "Honda",
  "Nissan",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Hyundai",
  "Kia",
  "Mazda",
  "Subaru",
  "Porsche",
  "Lexus",
  "Tesla",
  "Jaguar",
  "Land Rover",
  "Volvo",
  "Mitsubishi",
  "Ferrari",
  "Lamborghini",
  "Aston Martin",
  "Rolls-Royce",
  "McLaren",
  "Bugatti",
  "Maserati",
  "Alfa Romeo",
  "Fiat",
  "Peugeot",
  "Renault",
  "Citroën",
  "Opel (Vauxhall)",
  "Skoda",
  "SEAT",
  "Mini",
  "Jeep",
  "RAM Trucks",
  "Dodge",
  "GMC",
  "Buick",
  "Chrysler",
  "Acura",
  "Infiniti",
  "Genesis",
  "Lincoln",
  "Cadillac",
  "Suzuki",
  "SAIC Motor Corporation",
  "BYD Auto",
  "Geely",
  "Changan Automobile",
  "Great Wall Motors",
  "Haval",
  "Mahindra & Mahindra",
  "Tata Motors",
  "Proton",
  "Perodua",
  "Subaru",
  "Geely",
  "BYD Auto",
  "Mitsubishi Motors",
  "Peugeot",
  "Citroën",
  "DS Automobiles",
  "Renault",
  "Alpine",
  "Dacia",
  "Hyundai",
  "Kia",
  "Genesis",
  "Samsung Motors",
  "SsangYong",
  "Isuzu",
  "Mazda",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Referral Program", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Facebook", url: "/https://www.facebook.com/" },
      { title: "Instagram", url: "/https://www.instagram.com/" },
      { title: "Twitter", url: "/https://twitter.com/" },
      { title: "Youtube", url: "/https://www.youtube.com/" },
    ],
  },
];
